// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FirstToolWin
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidFirstToolWinPackageString = "6ab8e94a-6972-402d-b811-dd16879c6ee7";
        public static Guid guidFirstToolWinPackage = new Guid(guidFirstToolWinPackageString);

        public const string guidFirstToolWinPackageCmdSetString = "e484ec28-2027-4cc4-b6b3-d7e8450f6f8b";
        public static Guid guidFirstToolWinPackageCmdSet = new Guid(guidFirstToolWinPackageCmdSetString);

        public const string guidImagesString = "f2871bce-d02b-422a-83c9-f848ab698146";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int FirstToolWindowCommandId = 0x0100;
        public const int ToolbarID = 0x1000;
        public const int ToolbarGroupID = 0x1001;
        public const int cmdidWindowsMedia = 0x0100;
        public const int cmdidWindowsMediaOpen = 0x0132;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}