// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FirstMenuCommand
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidFirstMenuCommandPackageString = "d7798d23-77ba-48d0-9584-1d803ec24f85";
        public static Guid guidFirstMenuCommandPackage = new Guid(guidFirstMenuCommandPackageString);

        public const string guidFirstMenuCommandPackageCmdSetString = "f15ee506-c711-433a-b8cf-05f4cd932166";
        public static Guid guidFirstMenuCommandPackageCmdSet = new Guid(guidFirstMenuCommandPackageCmdSetString);

        public const string guidImagesString = "67d84b7a-a04b-45d6-b1ba-52ae864933bb";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int FirstCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}