// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TopLevelMenu
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidTopLevelMenuPackageString = "fab362e7-2112-4732-b493-532ecc25ff02";
        public static Guid guidTopLevelMenuPackage = new Guid(guidTopLevelMenuPackageString);

        public const string guidTopLevelMenuPackageCmdSetString = "feb676ff-8fc5-4845-b8b2-5b5884d5aafc";
        public static Guid guidTopLevelMenuPackageCmdSet = new Guid(guidTopLevelMenuPackageCmdSetString);

        public const string guidImagesString = "cf351a93-6b74-40f1-b12c-0d259dd50c6e";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int TestCommandId = 0x0100;
        public const int TopLevelMenu = 0x1021;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}