// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXProject3
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSIXProject3PackageString = "bf4b23b2-1b76-4b26-8009-5993bcd48a13";
        public static Guid guidVSIXProject3Package = new Guid(guidVSIXProject3PackageString);

        public const string guidVSIXProject3PackageCmdSetString = "f8c7b7c5-b145-419c-a92f-81c354a52664";
        public static Guid guidVSIXProject3PackageCmdSet = new Guid(guidVSIXProject3PackageCmdSetString);

        public const string guidImagesString = "16f2717e-97f5-4b8f-bae5-ea3afb6b1f94";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ToolWindow1CommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}